{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.3.6/identity-0.3.6.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.3.6.klib",
          "url": "identity-iosarm64-0.3.6.klib",
          "size": 1040472,
          "sha512": "6b6bb3b5975c39919aaeacbe1418f4f9937fcfe27d8c73bf9f5fd3bca649d3de70fa91eb1fc8745eb4c80fa40a0d3c4a9034da4f4808da22f85ab67c49cc8027",
          "sha256": "b25f1134f8400735ccab40f3288cd580d7226e35a1681b44306ec0b7db827fc8",
          "sha1": "aaf90331b9b1f8dc1337283be6c105a366fd4127",
          "md5": "6724af9dc35e4e202b24e053ad4c121c"
        },
        {
          "name": "identity-iosArm64Cinterop-iProovMain-0.3.6.klib",
          "url": "identity-iosarm64-0.3.6-cinterop-iProov.klib",
          "size": 4404,
          "sha512": "4b592a9d7011645977f0120ae4c270ff238f32d9c92b82f4e5b5df526f807cda446f3f70724766a0bf3a63bb9bd4a7ffcff1df5e6a003ac8e3e19e2ca7ce7f22",
          "sha256": "f047a2f7ec6d2fa769d81b466813228915a10edd4f558a538709570cea783384",
          "sha1": "17a4be4e7278463b507a7b1d864c8e8384ce208b",
          "md5": "667bac9f6a71d5ffcb0e898924a97796"
        },
        {
          "name": "identity-iosArm64Cinterop-JOSESwiftMain-0.3.6.klib",
          "url": "identity-iosarm64-0.3.6-cinterop-JOSESwift.klib",
          "size": 6826,
          "sha512": "ba4a0b54821d2ede5a47b5ebda3a8992201bd7a423052871ebcbdecd298eb048a2048bbd93caf9f4012b7eb4e03dbb15317b69481b8f5d327ba5d4e16d4de132",
          "sha256": "ff7b7d5fc0c9a701ea56d5b124ee1129900f75aaf6a714ce838da836616c18cc",
          "sha1": "fe879c0d9abf5078d9b1406bda6612d9610695b7",
          "md5": "fcdc6d0393ae8b085976a86f19134546"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.3.6.klib",
          "url": "identity-iosarm64-0.3.6-cinterop-cinterop.klib",
          "size": 2070687,
          "sha512": "0840e5e86a4caffc14373065fff4eb344943a8c51d1a5519d868ad4e1d7fdb1e6e2db7430114ebc1c8a59cf08625556d26f57d750fb1a4c9d2267b8bc7516670",
          "sha256": "673f9b4583c04d85501e8ba4338aedb0a93086666a0a6f65b7f63921b99d132a",
          "sha1": "17e90f3dceb1970892b900f4cf3810295ed16be1",
          "md5": "efe09ef50f5b39d565d0492a336f774a"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.3.6-sources.jar",
          "url": "identity-iosarm64-0.3.6-sources.jar",
          "size": 163077,
          "sha512": "0f12789b675a2bb940c14a021b19e5f1920aa8e8d10f03548e779e91e5f875257495c307745a02fc17dbe1d9a94e49f18ca7385ca0da39bc039558c300a3fa6d",
          "sha256": "21fe66bdf4dc560fc54574bbed73442e015c7539e5bf09c1dfb201f0907e5bec",
          "sha1": "76ac8ef1def79f344da8c9daba9b65d0fd208513",
          "md5": "d38ccb69f93acdf4cf5f36e93b7652f0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.3.6-metadata.jar",
          "url": "identity-iosarm64-0.3.6-metadata.jar",
          "size": 261,
          "sha512": "2aa29bead55435798cf2081a5fa959cc09c1032426f1972cc49c5b04d87e52d8929c590e077129114db774b5a980eb74825cd4985353e15c6b1d3dfa3d07776d",
          "sha256": "f4e7a5d861eeba611d98dbb917753f11b80d79e1fce9cd08654a414f284e4b83",
          "sha1": "66c60347cd3dcaabe842b2ad16814e40a05515c5",
          "md5": "a58d5c34264f52b1943c083fb562fde3"
        }
      ]
    }
  ]
}
