{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.4.1/identity-0.4.1.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.4.1.klib",
          "url": "identity-iosarm64-0.4.1.klib",
          "size": 1184296,
          "sha512": "e8f1ae402fa839e459ae80967640985bd0bd23bfa15be01c23c0ba935d370f2982d69880c5736cfa2fdd82b8675217966207885a912e49a888b5fbf35cfd20e9",
          "sha256": "39d6e7417b0b95dcf627dfc0bfcadeef75d258bf5dc0dee2c97b58fbf12279a4",
          "sha1": "79d09ad8e91024889a52b805a8f46254c6f7e603",
          "md5": "4c4a0042329cd4228402ca36f936437a"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.4.1.klib",
          "url": "identity-iosarm64-0.4.1-cinterop-cinterop.klib",
          "size": 2070687,
          "sha512": "e9a092e8bd89e91eafe9ee17595396876cac4cdf151daf7535cea6559531469bfb780dda145864409b719763ec2736c28248dc3408e4e65d4bfc4123b12e7b96",
          "sha256": "50f0bb30c442dd876d3eef26094d70ad0450916fa57f0692554b82064a4dfdfc",
          "sha1": "c7481471ec8ec3a2d3453d4765f9143a849a0247",
          "md5": "2c0757ddd0e09fc46c16482127b19ee6"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.4.1-sources.jar",
          "url": "identity-iosarm64-0.4.1-sources.jar",
          "size": 188409,
          "sha512": "35a5faffb335c81408dbfd48a1e412da217777a72d15e8e6fedf4f4142f6ceecd327b0294e3c32b95b729a459375138bb26d34f86bf6fa7249bc190200f8e284",
          "sha256": "5a3decc0b8964434c52dda078523c12fdb4f1eab52f30d352ac2b77e4a2bece3",
          "sha1": "1ed83914bf3f315affc9d7adb855fcff4a1dad47",
          "md5": "6d5db169a22005239932857b6acc7651"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.4.1-metadata.jar",
          "url": "identity-iosarm64-0.4.1-metadata.jar",
          "size": 261,
          "sha512": "3a3da3cbf84727f01abc7c864bfc46f7d014caedac85fd78548af706f1ee7b0e56f358e15507caed6de2edb4670fbed5b066cb901b852d4cfe008039e60049d5",
          "sha256": "d7c95a3fbaee6187045c4fe5f571af7cf8f5994cb53afc53dff2471757743b81",
          "sha1": "15ab5749dd8886395ce122d0f11831fbe1f2d68c",
          "md5": "7b6b42eda00c6e8da590ff69dab17c4e"
        }
      ]
    }
  ]
}
