{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-0.3.2.jar",
          "url": "identity-0.3.2.jar",
          "size": 74666,
          "sha512": "d4265632e935b7b9ec2957ebc3e3a8aa69017be5f96e58acfe776bad894b293b0c1a8bac4b7bec1493b38b2f03b78475adf1a140bfdf6504fd58bc6869b5c23c",
          "sha256": "2e366363172227b56d4bda0d5eeaadda4046184af036f5d1da58895e03ccdc0a",
          "sha1": "8552869018efbba2d89915e9affdeac35e8bf28d",
          "md5": "6384d683c0815dda234ade690a42d7ad"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-0.3.2-sources.jar",
          "url": "identity-0.3.2-sources.jar",
          "size": 83392,
          "sha512": "baddf5092ff7c6a3dbfc153c1fa1feda6d6f4c3b787516a614a2bb100f46014ae5469242c24aa76373802c50137960c612879156ec79b81e4fad740aa291385e",
          "sha256": "3cd5ab26a21c227f1365c7a7d26a20531b3d42689591eef1673b86834bf317be",
          "sha1": "c58087dcd284daf5fb5bef71a0795f0d6c5d92c1",
          "md5": "f36c40a11f55009289117fa7cdb438b3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.2/identity-android-0.3.2.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.2/identity-android-0.3.2.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.2/identity-android-0.3.2.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.2/identity-iosarm64-0.3.2.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.2/identity-iosarm64-0.3.2.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.2/identity-iosarm64-0.3.2.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.2"
      }
    }
  ]
}
