{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-0.4.0.jar",
          "url": "identity-0.4.0.jar",
          "size": 104253,
          "sha512": "d9fd7cdf89ca7c0e60345ce6d611f706c4dfc11d507cc39cb5fbf8888d5c5526d9118c95a4f0e66c5be2df51b51d2cc05878ed1a5e311757e170030731d04d5c",
          "sha256": "df67a485cebc4ca2dd9cddf1556ca4b90c0bb7cf464c3ace4e6870585d635e7c",
          "sha1": "6331bb164c266c6ca5e8618488f873f75ef435a2",
          "md5": "02c159706f078ab2e2040935ce2ead4b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-0.4.0-sources.jar",
          "url": "identity-0.4.0-sources.jar",
          "size": 142133,
          "sha512": "8c468ac13f7974d17db944b9e7b5c07f0b387430e951103b1d6ce7f4009bc229f9ae8cc2d0265f4baad6750d9ea9ddee3b3c6d47a2056f998804fb13259813b5",
          "sha256": "7bec668fb676b483b6705460f6217a5c38e9d7bd0d6b417f7b28e6173ab212a6",
          "sha1": "29d85d9018b0ac68ff662c4b4865f38986c29951",
          "md5": "3bd816a50733599bcf7635d86ed8020d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.4.0/identity-android-0.4.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.4.0/identity-android-0.4.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.4.0/identity-android-0.4.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.4.0/identity-iosarm64-0.4.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.4.0/identity-iosarm64-0.4.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.4.0/identity-iosarm64-0.4.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.4.0"
      }
    }
  ]
}
