{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.3.2/identity-0.3.2.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.3.2.klib",
          "url": "identity-iosarm64-0.3.2.klib",
          "size": 771730,
          "sha512": "423ce17cded6081c618ab9188b6465ae1a04bb2ab71e59af9a4894deb2f88a9783e6c47e1b435b26ee8075b07ff959fcdc7b109a4aed81ed89c62d8df107418c",
          "sha256": "4a7e484c9e39a68e97d4117903335df22e73d5a80c74b793b2b12afabc854991",
          "sha1": "35223d5489207f60bffe16c66511203223c10aac",
          "md5": "bc1e1a1569b9604bb63c71f7409d5fc3"
        },
        {
          "name": "identity-iosArm64Cinterop-iProovMain-0.3.2.klib",
          "url": "identity-iosarm64-0.3.2-cinterop-iProov.klib",
          "size": 4404,
          "sha512": "5f3a32553fdc58c7f8c3adbbb933a9e62babd09b6d2b17946894acce1c4f905b21e0b88f93b815f87d5ce89e5a2647e88d43294731dc30114e5e139290279190",
          "sha256": "a6574363b299e686c9178377ae098a9bd651cf6514dfeab2cdd97d26c91a3504",
          "sha1": "eac24465c2211b753aeaa8314fd126f6479a2609",
          "md5": "f10fb514edb655d497a7a21a1e4be118"
        },
        {
          "name": "identity-iosArm64Cinterop-JOSESwiftMain-0.3.2.klib",
          "url": "identity-iosarm64-0.3.2-cinterop-JOSESwift.klib",
          "size": 5347,
          "sha512": "47ef04c90293898269d951107eb78393237a5d5e1abdf98a0b96a5053f70c37f99d0b59110fc9727c1c46137ea077b0e15e9455b08e5ba433624b44661857f90",
          "sha256": "e888a7e71044e45041b446d7bb637b50ae16ab732c94398d252756f230b7f1a1",
          "sha1": "e8c31c513d7fdd7cb9e28640974eb47bed987b8b",
          "md5": "df757ceaf2c91c43677881cdbd5e07a5"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.3.2.klib",
          "url": "identity-iosarm64-0.3.2-cinterop-cinterop.klib",
          "size": 41918,
          "sha512": "8ffe0eabc215f6b52759faf4684cd0b1e86ea6cc8648e105f95a711446eb23362952a7954391a9eb9bbe95a12e8d0337ca7cfeead55d41b0009ca4cc846f7e51",
          "sha256": "b3432ec0d2f737d8b0cf15ad6f6052530fa46494ddea6aa0e2c3ac1290b2d2cc",
          "sha1": "83d47da1864f1c13521a02c358f243ca6014c620",
          "md5": "daf41b85641ad01e2d3baf264af4ca6c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.3.2-sources.jar",
          "url": "identity-iosarm64-0.3.2-sources.jar",
          "size": 113644,
          "sha512": "d2f4a1df0bf8a7b04120b42ac760a83c93032b70e478772ea7e7f5e09cbecf906aab2a462031d5c572df9a92d39f1870f8f90d50fd9ed6434de46c56fe6ce665",
          "sha256": "2e588bb582016fd80ec51601e1ee92ff4ffb26fa6463aa7780414696fec95c7c",
          "sha1": "f2c128c725124fd3448050569c80173e910e9861",
          "md5": "bfe9b11794442eea4b13c5d825884b7d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.3.2-metadata.jar",
          "url": "identity-iosarm64-0.3.2-metadata.jar",
          "size": 261,
          "sha512": "31d16f707012a775045d6d7784f609dfcf471760cd4665d37592f13a6cd6f2f3301aa54e230ca19930e2f8962648e5c84af3835a08d7b26374005709e7a5b318",
          "sha256": "d4d898fd4aec63169b583aa15aa541bbbde383f11c21216c07b50ba0d9913f31",
          "sha1": "ecbb314ec45511f52c79d750fe834aabe5cb4f33",
          "md5": "1e228f653ca530ae3d879ffeda4d0510"
        }
      ]
    }
  ]
}
