{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.4.0/identity-0.4.0.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.4.0.klib",
          "url": "identity-iosarm64-0.4.0.klib",
          "size": 1157533,
          "sha512": "584a032762d187c88b1dc856434b5ddfdf7f36ebe7f12c20002aa0435500a4c071a7bf84dd2a38c8d2c9bb26bad874f0218364bbd833b25e4e25845a614dfe7a",
          "sha256": "3e4a66e8068da5d95a41b686525911332a63c384496859b3d7c68e379dbc1d20",
          "sha1": "5f887d85a5db1da5b3183bfcce08e6d92163ec0a",
          "md5": "9b97f5d7b99635c6ce2d866152da7af6"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.4.0.klib",
          "url": "identity-iosarm64-0.4.0-cinterop-cinterop.klib",
          "size": 2070986,
          "sha512": "3a3012c8fe00ded67926a81cfb3ccf656467f0a40eb3d54885bb0d19a9fa8aa9f2187d645be9c7a760f1b598be2765f08108ad713053785f1deb426006677e6c",
          "sha256": "7d80199e477f656625fab8530d6e66b41f0262232671605c9f2e7ac2aa671c9f",
          "sha1": "4e64c4cb3ab851b90c6ef25b5a99bb2861addcf9",
          "md5": "b7c7fc05460f47db2140c97526f57cb3"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.4.0-sources.jar",
          "url": "identity-iosarm64-0.4.0-sources.jar",
          "size": 183276,
          "sha512": "0dc5b5630815865f326121e6fe31b5e1fec7731d29d21bcf5d8bb506f050c3be00ce6797cfd7344d35f0f005532229a6e3002a9e2bc56307ae7d6867df0574a7",
          "sha256": "ead44246b29431d5b80021e10a5965078fd213f5201f8d2d5979c4b1b9e780f3",
          "sha1": "3b4f246941166096c7bcaa0b13950b4c9d8fcfdf",
          "md5": "abb0fccfb26798dda42e752fe95fd838"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.96.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.4.0-metadata.jar",
          "url": "identity-iosarm64-0.4.0-metadata.jar",
          "size": 261,
          "sha512": "d5e3bf20c66e5471f5ba2e5c7dba8335bf54c60622079b65d8aa1a876c2fadc2e9a2915b94d7caaceb5663207118f72410edb2fbb791772cb385da7726545e63",
          "sha256": "bcb5b6c49d33405a9c0d105db58f9ea8edaef86129198dba49528065b7064408",
          "sha1": "c47a13f64e1c5c6c7e9c670d65b80ab5ccc313bb",
          "md5": "bc08559a74030e31975d231f4f0dc5ff"
        }
      ]
    }
  ]
}
