{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.3.3/identity-0.3.3.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.3.3.klib",
          "url": "identity-iosarm64-0.3.3.klib",
          "size": 779051,
          "sha512": "a3ca364248647be54b3496d1c3443d575c13cc08dbec3fe403ce0e2d384b36d988142b2b2c3d53b665eef2ec348fb18eccfbcbe3250f3cd1916f0c9b37f1609b",
          "sha256": "36cc5f788dda06f98b181dd95a6680b4f6da1d62e769b8746dd65c228868a2ef",
          "sha1": "bae9dbb1c7b62f93045d01f6a2bf3b8d56ccc784",
          "md5": "65a9e9feec749a25f8a8b83720b33d34"
        },
        {
          "name": "identity-iosArm64Cinterop-iProovMain-0.3.3.klib",
          "url": "identity-iosarm64-0.3.3-cinterop-iProov.klib",
          "size": 4404,
          "sha512": "5f3a32553fdc58c7f8c3adbbb933a9e62babd09b6d2b17946894acce1c4f905b21e0b88f93b815f87d5ce89e5a2647e88d43294731dc30114e5e139290279190",
          "sha256": "a6574363b299e686c9178377ae098a9bd651cf6514dfeab2cdd97d26c91a3504",
          "sha1": "eac24465c2211b753aeaa8314fd126f6479a2609",
          "md5": "f10fb514edb655d497a7a21a1e4be118"
        },
        {
          "name": "identity-iosArm64Cinterop-JOSESwiftMain-0.3.3.klib",
          "url": "identity-iosarm64-0.3.3-cinterop-JOSESwift.klib",
          "size": 5347,
          "sha512": "47ef04c90293898269d951107eb78393237a5d5e1abdf98a0b96a5053f70c37f99d0b59110fc9727c1c46137ea077b0e15e9455b08e5ba433624b44661857f90",
          "sha256": "e888a7e71044e45041b446d7bb637b50ae16ab732c94398d252756f230b7f1a1",
          "sha1": "e8c31c513d7fdd7cb9e28640974eb47bed987b8b",
          "md5": "df757ceaf2c91c43677881cdbd5e07a5"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.3.3.klib",
          "url": "identity-iosarm64-0.3.3-cinterop-cinterop.klib",
          "size": 41918,
          "sha512": "8ffe0eabc215f6b52759faf4684cd0b1e86ea6cc8648e105f95a711446eb23362952a7954391a9eb9bbe95a12e8d0337ca7cfeead55d41b0009ca4cc846f7e51",
          "sha256": "b3432ec0d2f737d8b0cf15ad6f6052530fa46494ddea6aa0e2c3ac1290b2d2cc",
          "sha1": "83d47da1864f1c13521a02c358f243ca6014c620",
          "md5": "daf41b85641ad01e2d3baf264af4ca6c"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.3.3-sources.jar",
          "url": "identity-iosarm64-0.3.3-sources.jar",
          "size": 114603,
          "sha512": "c607fc4d7cb8e1f7ad4a9abad260f550dc2e507846c971d652ded39ebafc0880a78ee45a00e7bb292587750019f6795a3e8a762a04838d80815c431a733153f4",
          "sha256": "025f5e1759b35fda2cf6a256a9ea547d40da33315c0fa43089ec9aafb435c4f9",
          "sha1": "5aa87f8c16cdb0cb119a01e20d6472a2d73772cf",
          "md5": "2559957e52b95edaec9482ac2c0f20e7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.3.3-metadata.jar",
          "url": "identity-iosarm64-0.3.3-metadata.jar",
          "size": 261,
          "sha512": "100d9213ce51bb142e0b259f58762f2dd8d1ed0f93d05b9c9de0b66938d5fa5f5b2dc20d77ab554f82ebc0b447da81056a3aca99d1788ba92c9e3db23bd32d28",
          "sha256": "e77417d90920c5c0bff886b415f64a99fd26fc4d880c54cc21007cf5c88f71d8",
          "sha1": "bf2a4d5db55eb42c14cb572d7dec66408c88d759",
          "md5": "8e449db40783f4dd230a3fcdad9b2e79"
        }
      ]
    }
  ]
}
