{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-0.3.1.jar",
          "url": "identity-0.3.1.jar",
          "size": 74665,
          "sha512": "b09397285c5a3688191debd2cdafcd136c14505d0e0163524faef8bed5b5c1b6a37109b59322a869e658f4a01db6676a33a6a28a9989479822759564c3d3baa6",
          "sha256": "825968de83cf9daab7b865af4c3a557ca589837c5eff3406bcc797c1bf651849",
          "sha1": "9c4e015089ed9ff4187d20e45373e989559f9cc0",
          "md5": "0c303a4c43ef4bcdf775b82e01f63fd6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-0.3.1-sources.jar",
          "url": "identity-0.3.1-sources.jar",
          "size": 83357,
          "sha512": "3184c9278f2614eb8981a4564f9a62a8a54c3154162e55c901203d16de2dd9c2340f841f25e752ae96b386d087cb3d9b0caccf0e59316540d4114a2f08a8493f",
          "sha256": "da58bc9d485442da1ffe49c9e5083495089cf5287bc8e1f82bb7e235c205390f",
          "sha1": "58e23f94eb208263167b45af03c73470716f7824",
          "md5": "b97988fd26b299d1951bcfcd2d650681"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.1/identity-android-0.3.1.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.1/identity-android-0.3.1.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.1/identity-android-0.3.1.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.1/identity-iosarm64-0.3.1.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.1/identity-iosarm64-0.3.1.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.1/identity-iosarm64-0.3.1.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.1"
      }
    }
  ]
}
