{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.3.1/identity-0.3.1.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1.klib",
          "size": 771429,
          "sha512": "277e975fc8cbae3709702d7f90c5c86a2bc2e483d54a0650bbe122e580868feb33dd285dadffcc1f40c7c3afbac5c430272fa7c289c566b4e0de335ae662080f",
          "sha256": "9234ac650fd549b13e8e80bc77eea8d0193e825b930a52d8720490b54f3744ee",
          "sha1": "2239454c8fcfc044189f99f6e12ecb475c9ffdfe",
          "md5": "8b80d4dcdfc5b7b7a5b970afa61c85cb"
        },
        {
          "name": "identity-iosArm64Cinterop-iProovMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-iProov.klib",
          "size": 47010,
          "sha512": "394f85c3139501391670c0de1e344698a665e643e39a4243f939db14506667c9906fac6847ac188b369a1adccd08c57b8bc80344a1387d7ccb8b43118a1cd5b2",
          "sha256": "4893d5d4849fddf2a5e61f33395f4c9f4fb92293f86c31a6faac93e98c9f8240",
          "sha1": "19a1b9a757e48784f5d72466ca2208e1366e13e2",
          "md5": "8d77f3fb580be9d1d892788008037920"
        },
        {
          "name": "identity-iosArm64Cinterop-JOSESwiftMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-JOSESwift.klib",
          "size": 5348,
          "sha512": "e63dabf002b501822a99f7fbdefa19fe00ae4a504c7efff1d8ffbc7ebd4b482a9cd39675f3aca95290e47b2abbaca13495cb1087565cf7fa133b42b63ae9ef92",
          "sha256": "b65f3cdc455d036f7cfd1bf8370433c3c40f1d773f7adbfe393064e877750991",
          "sha1": "fa24b22a03a600217da2e16a2aeee7ab87c3c244",
          "md5": "dcb75aad224f9ffe18d11c807f43039e"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-cinterop.klib",
          "size": 47997,
          "sha512": "937384d812558d719bf01bf350e36fdae5ea18f558222540983ca99a96f8e49ef7ce1c030eb39b50ef2df1212042beb5ca8c279a4b020e6c027ce1b54ba7ea66",
          "sha256": "6b21cf72fca09a9ee8ff4cacbeca45fc43704d8484905ae31b5f4f6cb64fc171",
          "sha1": "3eb11a40fd3fe9a73fb3910c0d554dcdef74405e",
          "md5": "1851ee8550fd3c5e6d1e9acb1eab7526"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.3.1-sources.jar",
          "url": "identity-iosarm64-0.3.1-sources.jar",
          "size": 113613,
          "sha512": "cc5439ec0735b260972ab0fef4237518316638fb91086d69ebccbf5441770cb47f47c841cca492d1f583e47805023654e0192ec08c2a6f12cec75c393f2a8de1",
          "sha256": "c9d1d6867d8c40d2f2fa3020285f88f38baf10bbffc1cee954ffda5381ab882f",
          "sha1": "903d65f884d981487a8bb4073ec06ea5be06d5fc",
          "md5": "c3579bd34e12d291c9f5a0673a7afe2f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.3.1-metadata.jar",
          "url": "identity-iosarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "c82eec270f142ccf4806575e785d208258459aabb45584794060dd7ef992d1bb26ba0cb5c13c0267f3321a36e4afda2dca289a787fd5ba256a9ae55640a1ce43",
          "sha256": "0fad05ed21b4d6ea57181890c05d3613a6db46aca87e3bb0b70702f6b7fa3428",
          "sha1": "4cd60ce854b388b7120570c8dbaaede6b4c414b8",
          "md5": "bf6b5605df991ab8c4c538af4b679e54"
        }
      ]
    }
  ]
}
