{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.3.1/identity-0.3.1.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1.klib",
          "size": 770994,
          "sha512": "f4ea06cad34358824b39a7b0cc9c5000777c48690b4232fe5b97e46c27dc945fb39b633a39ebcbc605ae6f86022546023adbadf18a87d26c2a0aace8df46761e",
          "sha256": "925a3a73fc75bffa210568be4ed93c266acc9a1ab553ff91c5e63934f51ca075",
          "sha1": "a8a20d6815a9b58f06d57c2da3b74f099a14201a",
          "md5": "86c2dbe2d8855125efa8de1b7a7d7e68"
        },
        {
          "name": "identity-iosArm64Cinterop-iProovMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-iProov.klib",
          "size": 47010,
          "sha512": "394f85c3139501391670c0de1e344698a665e643e39a4243f939db14506667c9906fac6847ac188b369a1adccd08c57b8bc80344a1387d7ccb8b43118a1cd5b2",
          "sha256": "4893d5d4849fddf2a5e61f33395f4c9f4fb92293f86c31a6faac93e98c9f8240",
          "sha1": "19a1b9a757e48784f5d72466ca2208e1366e13e2",
          "md5": "8d77f3fb580be9d1d892788008037920"
        },
        {
          "name": "identity-iosArm64Cinterop-JOSESwiftMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-JOSESwift.klib",
          "size": 5348,
          "sha512": "e63dabf002b501822a99f7fbdefa19fe00ae4a504c7efff1d8ffbc7ebd4b482a9cd39675f3aca95290e47b2abbaca13495cb1087565cf7fa133b42b63ae9ef92",
          "sha256": "b65f3cdc455d036f7cfd1bf8370433c3c40f1d773f7adbfe393064e877750991",
          "sha1": "fa24b22a03a600217da2e16a2aeee7ab87c3c244",
          "md5": "dcb75aad224f9ffe18d11c807f43039e"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-cinterop.klib",
          "size": 47997,
          "sha512": "937384d812558d719bf01bf350e36fdae5ea18f558222540983ca99a96f8e49ef7ce1c030eb39b50ef2df1212042beb5ca8c279a4b020e6c027ce1b54ba7ea66",
          "sha256": "6b21cf72fca09a9ee8ff4cacbeca45fc43704d8484905ae31b5f4f6cb64fc171",
          "sha1": "3eb11a40fd3fe9a73fb3910c0d554dcdef74405e",
          "md5": "1851ee8550fd3c5e6d1e9acb1eab7526"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.3.1-sources.jar",
          "url": "identity-iosarm64-0.3.1-sources.jar",
          "size": 113634,
          "sha512": "8431e95fb80d319a881b542490006d2efa83343bcea5d622e5a0d4e651a694b57a49a237f4ce1410aa5ac81ab8aefc75800e92b75fc6137ddf20ddfb91499dd6",
          "sha256": "fb32524f4756317e357bae1757052ff895ba56ec7ecc8d6186c1f13293ba8459",
          "sha1": "1f850eb80cef0b53288d994848b4fe1596a2d252",
          "md5": "fdb7ea1403abfbfd6b1b4e605564fd85"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.3.1-metadata.jar",
          "url": "identity-iosarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "56429799bf3c4df6c84d5f11430e6e5100c337c2010b4a27f0aef538bfbbf8ef3ee2606ba91b1d12f6e9231874b61e3a554b75d483ab1760fc79e0333b52a604",
          "sha256": "12fee7fd98ab2054ba717a396ac9e92d5960bb7d3ee3a87b86c97d6f3d0ae6c2",
          "sha1": "a00e56edbc3759252e0872f917aecfaa347e953d",
          "md5": "e0fca21131cdad717fa89bb8ae2c41a0"
        }
      ]
    }
  ]
}
