{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.3.1/identity-0.3.1.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1.klib",
          "size": 761596,
          "sha512": "fd4e022e7349eddfdd1aa3201df84e50a90a06ae77dd0c129e09114b4b0ca10ed4a7afce09f957a7d02b852a0a85c6b4be7d70066082e2713553bd3eb80e9c6a",
          "sha256": "772efbf01e9c8a4f779aada835c6e87c203bb000e90d71e0ff671d1b719d8de3",
          "sha1": "636f37a70ad98333c22a5a39075e7250b0f3298f",
          "md5": "a8f7093c54fcaead2358e63fc557841c"
        },
        {
          "name": "identity-iosArm64Cinterop-iProovMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-iProov.klib",
          "size": 47010,
          "sha512": "394f85c3139501391670c0de1e344698a665e643e39a4243f939db14506667c9906fac6847ac188b369a1adccd08c57b8bc80344a1387d7ccb8b43118a1cd5b2",
          "sha256": "4893d5d4849fddf2a5e61f33395f4c9f4fb92293f86c31a6faac93e98c9f8240",
          "sha1": "19a1b9a757e48784f5d72466ca2208e1366e13e2",
          "md5": "8d77f3fb580be9d1d892788008037920"
        },
        {
          "name": "identity-iosArm64Cinterop-JOSESwiftMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-JOSESwift.klib",
          "size": 5348,
          "sha512": "e63dabf002b501822a99f7fbdefa19fe00ae4a504c7efff1d8ffbc7ebd4b482a9cd39675f3aca95290e47b2abbaca13495cb1087565cf7fa133b42b63ae9ef92",
          "sha256": "b65f3cdc455d036f7cfd1bf8370433c3c40f1d773f7adbfe393064e877750991",
          "sha1": "fa24b22a03a600217da2e16a2aeee7ab87c3c244",
          "md5": "dcb75aad224f9ffe18d11c807f43039e"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.3.1.klib",
          "url": "identity-iosarm64-0.3.1-cinterop-cinterop.klib",
          "size": 47997,
          "sha512": "937384d812558d719bf01bf350e36fdae5ea18f558222540983ca99a96f8e49ef7ce1c030eb39b50ef2df1212042beb5ca8c279a4b020e6c027ce1b54ba7ea66",
          "sha256": "6b21cf72fca09a9ee8ff4cacbeca45fc43704d8484905ae31b5f4f6cb64fc171",
          "sha1": "3eb11a40fd3fe9a73fb3910c0d554dcdef74405e",
          "md5": "1851ee8550fd3c5e6d1e9acb1eab7526"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.3.1-sources.jar",
          "url": "identity-iosarm64-0.3.1-sources.jar",
          "size": 111563,
          "sha512": "93ab40372baae38db590d9b890c59e2e114e96e44a55353d0301f8b391c74f4dc40366f38a010484191a65fa9269a25986cde513e9da73f6151ad3c641336599",
          "sha256": "1030f429ec68b5b6674881a205f2ee44dbba8f5359290706ca21d757a4b43a6d",
          "sha1": "5797b5175310eb54a505a7d5f0d7dd763dc478aa",
          "md5": "e30ccc4a0fed9f94e82c294aa394a2c1"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.10.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-mdoc-credentials2",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "id.walt.openid4vc",
          "module": "waltid-openid4vc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "bcprov-lts8on"
            },
            {
              "group": "com.google.crypto.tink",
              "module": "tink"
            },
            {
              "group": "com.google.protobuf",
              "module": "protobuf-javalite"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-lts8on"
            },
            {
              "group": "com.google.protobuf",
              "module": "*"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcutil-lts8on"
            }
          ]
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.3.1-metadata.jar",
          "url": "identity-iosarm64-0.3.1-metadata.jar",
          "size": 261,
          "sha512": "a0e75d262af07dc4b14f2e87c66b18a51e1e5f0d104ac9e71fe41bf23964ea1a02df13a281ebebbac46c6249031072e5384cafadcf89c98e45e96c1cce4fcc9e",
          "sha256": "d740e01f93ade5c54dc6298ca39fa279695783c6ef6a4a840f8782ece92de849",
          "sha1": "770e00829ded3da3a6542695a007c97ff9dd697a",
          "md5": "822f070579424348c3186920ef026ed4"
        }
      ]
    }
  ]
}
