{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-0.1.0.jar",
          "url": "identity-0.1.0.jar",
          "size": 35123,
          "sha512": "6e186cc18be34db439637b53e8e36930ea6f3d727b5f105e204d6d852a78462aab4920db7c869ffd6c74fa3b3aedf5f3a825c616664b25d6a5c40a8f81bca299",
          "sha256": "4889601112e924e5111ff2ec734da62627211efaa0a831b0f73d2c986f27b0ff",
          "sha1": "d8e3ad15363ce75774e30c3b304273ccc75c30cb",
          "md5": "f4cbaf3feb25891c66b29f481823fac8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-0.1.0-sources.jar",
          "url": "identity-0.1.0-sources.jar",
          "size": 33766,
          "sha512": "4ae76ceb22488608cc8bc0f33d6d1e657832b873fe1bd3bbe85573b667963c99a8ed38ec2ee5b177d195d405a5fb1c9d719f6188fa43dbe8f53695f986708447",
          "sha256": "91e72395e31fbd44403fe331a2ba8efe94d7feee9a3d12dfd50d3a0d64c70b16",
          "sha1": "ded0b53b08ac99e6fcb6e0b32aa80123cdb0f279",
          "md5": "eee68996430d8ba320b189f6adc53976"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.1.0/identity-android-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.1.0/identity-android-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.1.0/identity-android-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.1.0/identity-iosarm64-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.1.0/identity-iosarm64-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.1.0/identity-iosarm64-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.1.0"
      }
    }
  ]
}
