{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-0.1.0.jar",
          "url": "identity-0.1.0.jar",
          "size": 34606,
          "sha512": "20ec03b93fc289ef04f8a5ddb0e0e821b46204a99e897663a66daaa946000c0f473fe5941f96eaae1522a7a2eb4806a076f571f3d2ff0e395c478f3f369c04b0",
          "sha256": "84f0181167aa73f2b7d56f7771c21d24444151ff84f1ff965bb16d0f9dd680f4",
          "sha1": "854a0155f24dcaba50303f5cbc64cab67fb07a8d",
          "md5": "533995b0b54db27bc173dbc0c3c8dc65"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-0.1.0-sources.jar",
          "url": "identity-0.1.0-sources.jar",
          "size": 32940,
          "sha512": "c00570bda3dd7d0ff9ecd76fc8cd805329b5f11940681157df6818feb0e8a53589b4a26e5d66c94d2ad00aa658ed5fc82331854e5297a2ee31798ba6361b08cb",
          "sha256": "3d7d3134656f26e71efd519360f32a459e6fb288ada8f3f8875ef51c265145c0",
          "sha1": "b3665e2571cbc5f171f26974305c87c94d720a17",
          "md5": "87b48473000fb4627dd9e2cdb8a67738"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.1.0/identity-android-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.1.0/identity-android-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.1.0/identity-android-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.1.0/identity-iosarm64-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.1.0/identity-iosarm64-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.1.0/identity-iosarm64-0.1.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.1.0"
      }
    }
  ]
}
