{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-0.3.5.jar",
          "url": "identity-0.3.5.jar",
          "size": 88794,
          "sha512": "f62ec29caa522e592de1269648aaed56aefb92ac4c58a260bdf31a183ddc5fad9220f617e91fe9fc02f4de91376b44036694d238611049ec485db88f1d6cda8e",
          "sha256": "390e41d61778648adbc831168717d8eba12eaed5c594accd45e59da3f68fd57e",
          "sha1": "dfebbad4c41180c9ace831eca00db81c63434bce",
          "md5": "c77b83856862780e7319116ad2bcf119"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-0.3.5-sources.jar",
          "url": "identity-0.3.5-sources.jar",
          "size": 114074,
          "sha512": "4653d612c06cad9d9b6af847bcbcf73445d43e55055cb1c29a63c7ebd353ad728d555247008e36337a59b078038b0e8f054b4f782efd894e518565d3354d41a9",
          "sha256": "8ea0705cb4d16e242f26c4670a1c6098f52ca74f4d0703ba78e72d476a7e248a",
          "sha1": "772b10023aa5824f4429318dd90d7152b047de28",
          "md5": "9f99e432286f79d4ec357e33195fad4b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.5/identity-android-0.3.5.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.5"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.5/identity-android-0.3.5.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.5"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.5/identity-android-0.3.5.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.5"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.5/identity-iosarm64-0.3.5.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.5"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.5/identity-iosarm64-0.3.5.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.5"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.5/identity-iosarm64-0.3.5.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.5"
      }
    }
  ]
}
