{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.5.0/identity-0.5.0.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.5.0.klib",
          "url": "identity-iosarm64-0.5.0.klib",
          "size": 1216061,
          "sha512": "8bcd3825d69deab4a42b4d8697bb0808506ec0b2963e0540d158616056fefe440549f428845e418451e801a595d4cabb139f902a0d59b8bbdcba8b2e66e464bf",
          "sha256": "7c3b6b00c6c612dcfc7cd1c216fc97782e1cc318b5664965abac84e344051fc6",
          "sha1": "01d5f1282ad623a4e7d768f24b291deed3cf42e5",
          "md5": "1fca4c0edd84e25a6633b1b813d23c59"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.5.0.klib",
          "url": "identity-iosarm64-0.5.0-cinterop-cinterop.klib",
          "size": 2077666,
          "sha512": "9fcd6df7309e34b63e4b03dc906fb0fe7ab86129b8a423de13367c87a3afe9983d1b9aa9c529dda7da509339d0fa59d9f5a982dbd8292376989f8e772033f1ca",
          "sha256": "3312cdec92de52ef143f3cee788ce7e0d9e46bb714107ff994baa99d14fa9c4f",
          "sha1": "df50a6ae19d6d78649dde853a4e6a2824e6921c9",
          "md5": "1f75f48799e2e60deab155fbe3c9ffea"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.5.0-sources.jar",
          "url": "identity-iosarm64-0.5.0-sources.jar",
          "size": 196483,
          "sha512": "f055fc0452215dcb042e225659da4eff35ba49a3d0a4472fe9eb0e3de1701f1ff2002f07f3749fedd5bab617e31bf0a4bf7694914af681c98de46d4dd3c33a3a",
          "sha256": "23a689f261c4341e4ba07f89117049456000a20f1ef8c246b63577833d95fe81",
          "sha1": "7bb6d629ea07d8232669d0e3c2d169ea27e5885e",
          "md5": "4cd316dde113d53f75592660bd6206f2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.5.0-metadata.jar",
          "url": "identity-iosarm64-0.5.0-metadata.jar",
          "size": 70755,
          "sha512": "4e34bf51d8a83f019ca91a05afb1d8ec98719573473caa82d41e2aeb83ba1ada88ad5c1953ae8f62e846e4f72f2f565e5995eb45f01a4cfc30beff087cd5f49f",
          "sha256": "693997850a89eb41ff1246ab06fef8208fffc072a2e07efad5fc5aa856aec6a3",
          "sha1": "0a39991cccfe25fb98a9ef3d11cfb475b652d1ff",
          "md5": "495001618f2e87c5f1664583389eea1c"
        }
      ]
    }
  ]
}
