{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "identity-metadata-0.3.4.jar",
          "url": "identity-0.3.4.jar",
          "size": 87122,
          "sha512": "bbd6bc429c1a56b00b154f358adb19fdcadc19fa0d5ec17686e5f2ff4167f725a09377b875b497e266b7202592de7ff18d2f7136dbea8e82062b99a1e3a731b4",
          "sha256": "e59e341c661b550991d73cebe3589d72815ea9401b63ee9ba12151b590330d2e",
          "sha1": "811aa68bb5403cf590e5258cd77a167ded3c589c",
          "md5": "61f1d8d44dd281d869a70e8d5b9d94b1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-kotlin-0.3.4-sources.jar",
          "url": "identity-0.3.4-sources.jar",
          "size": 109416,
          "sha512": "ff8d3f691f1dc1532ddd3bb73ac3a4e673256f36bab00a7ca7c624cbbfccc69bf5e26edf56b5396dccf23dff38081834ec5bfd4bc6b1e4d69963199701c4c053",
          "sha256": "b25b082e1fc51a668987ea17881ab9b62a311d564e76d8b1aa7f3bf4ea098537",
          "sha1": "c80fcfa78437d1c5bc0cb5a9736d53a21e383146",
          "md5": "8ffc9b1e251332492ddaab5009d569d4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.4/identity-android-0.3.4.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.4/identity-android-0.3.4.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.4"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.3.4/identity-android-0.3.4.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.3.4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.4/identity-iosarm64-0.3.4.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.4/identity-iosarm64-0.3.4.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.3.4/identity-iosarm64-0.3.4.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.3.4"
      }
    }
  ]
}
