{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.5.1/identity-0.5.1.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosSimulatorArm64Main-0.5.1.klib",
          "url": "identity-iossimulatorarm64-0.5.1.klib",
          "size": 1240527,
          "sha512": "4c7fd713eaf99450fefdc17a45ad8692d730331771a9bd3146cd585de86c557918f23fcdf848b103cc782cd40f003c4c4ffecb75232fc84654bbe1fe054b4588",
          "sha256": "c4813ec18fad1d902d398b1d3822ff3bf7355c2f0199aa12f3dcd6ddeb272a68",
          "sha1": "2535a3519b2e0c79938929df1a150730e4a2ad12",
          "md5": "e198348ec4f9245a3522dd2d7d1db1f1"
        },
        {
          "name": "identity-iosSimulatorArm64Cinterop-cinteropMain-0.5.1.klib",
          "url": "identity-iossimulatorarm64-0.5.1-cinterop-cinterop.klib",
          "size": 3980730,
          "sha512": "1494fca540c50c5ac34d8459d3388e8375d3b5f8a871217039d879570f589b5dcd85a3d7e9a81b733de0adeb9d793cf7204e0fa958a74c56307d8d2fe7a94003",
          "sha256": "fc7391d7611e145c6aac57165377ec3e89f37f563c625e9fb3ce47e3fb28c68b",
          "sha1": "05ad61e3d508b5cdad73f29acdd4aba2dfac416c",
          "md5": "1e26d5d5186e2350fa2363b0caa3a3d6"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iossimulatorarm64-0.5.1-sources.jar",
          "url": "identity-iossimulatorarm64-0.5.1-sources.jar",
          "size": 206703,
          "sha512": "d1293521786b5e21dc83ff617469b93c1f126974b3732e26b340d3afc34edb6cb98f14a7449e6a8659dd37f23544d149c3954d9e63b8e9a26feb90f520e7cbef",
          "sha256": "8b9427b6d8d3d68cafd2182ea122a082a8109a3a0e464978292ca9bd842bc646",
          "sha1": "c75069f204d3675921a430bff6daf8315e345609",
          "md5": "3ac018fd284b9a8bf1165a261115161d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iossimulatorarm64-0.5.1-metadata.jar",
          "url": "identity-iossimulatorarm64-0.5.1-metadata.jar",
          "size": 72449,
          "sha512": "6f1a120e2fdbf8d9836b4a0c150faecf3b9d4e6eee0cc363f60e0a8c7a7a6a8e23311f2f3864f107d6a7f438af6597fa537644f2144553bc01aedf1a4fdeecdf",
          "sha256": "f2aaa9f3a1b0f9bffd1f9de5f2388d4c1df09904f3c226b90c9409a947b1fc2b",
          "sha1": "805de3da19071cc699ebf3479b6fddbab1519bd4",
          "md5": "a273794ef54bfaf6ed20c03751aa7631"
        }
      ]
    }
  ]
}
