{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-0.5.0.jar",
          "url": "identity-0.5.0.jar",
          "size": 109862,
          "sha512": "4c966eb83a3bd75652244fde7b521ac12608feffd57778748cc6b0473c4c08a4472e96d8e121e948522b8bbdb6cd49b150f250dc32e945991c841f77ababe1e9",
          "sha256": "7aa488edbd41015fdd8dadefde3742f7d87b10670d7a7ad8f720bc54ba98afc3",
          "sha1": "c3e232aea7d6c1f434225bfa09bb6a80bc70d380",
          "md5": "181e891c8e71a391780fc603b6f86982"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "identity-0.5.0-sources.jar",
          "url": "identity-0.5.0-sources.jar",
          "size": 196483,
          "sha512": "f055fc0452215dcb042e225659da4eff35ba49a3d0a4472fe9eb0e3de1701f1ff2002f07f3749fedd5bab617e31bf0a4bf7694914af681c98de46d4dd3c33a3a",
          "sha256": "23a689f261c4341e4ba07f89117049456000a20f1ef8c246b63577833d95fe81",
          "sha1": "7bb6d629ea07d8232669d0e3c2d169ea27e5885e",
          "md5": "4cd316dde113d53f75592660bd6206f2"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.5.0/identity-android-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.5.0/identity-android-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../identity-android/0.5.0/identity-android-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-android",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.5.0/identity-iosarm64-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.5.0/identity-iosarm64-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iosarm64/0.5.0/identity-iosarm64-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iosarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/0.5.0/identity-iossimulatorarm64-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/0.5.0/identity-iossimulatorarm64-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iossimulatorarm64",
        "version": "0.5.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../identity-iossimulatorarm64/0.5.0/identity-iossimulatorarm64-0.5.0.module",
        "group": "com.iproov.identity",
        "module": "identity-iossimulatorarm64",
        "version": "0.5.0"
      }
    }
  ]
}
