{
  "formatVersion": "1.1",
  "component": {
    "url": "../../identity/0.5.1/identity-0.5.1.module",
    "group": "com.iproov.identity",
    "module": "identity",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosArm64Main-0.5.1.klib",
          "url": "identity-iosarm64-0.5.1.klib",
          "size": 1240455,
          "sha512": "3857185cd1f25e97e9a3ab465b1e26426e0aff0c7ebb87f67e796aeeedfe2a5f09856706a7f3b21168644111d4917ab0593738cefaa6ff757a9b812cb2a0b45d",
          "sha256": "a3e357925abaef9eb233ffc47a96debdf46ef40a3ca92daa3f628eb27ac6f22f",
          "sha1": "e56136ea03a34dca73a67692795178bf3510c5c5",
          "md5": "2243d20d85e97a06439636eeb57109b1"
        },
        {
          "name": "identity-iosArm64Cinterop-cinteropMain-0.5.1.klib",
          "url": "identity-iosarm64-0.5.1-cinterop-cinterop.klib",
          "size": 2087939,
          "sha512": "58d39a1e3ee9ed6a92ade982a62ef86637591334da300b6041683fccd2a6b0580bf3097061fdb344ee1e28271c019811d8d2d00392d7714423072e8af52a8dd3",
          "sha256": "fb176832a705b4faae95a2513b4cb66214dc24729112ce6692ea9ec8fb7cda23",
          "sha1": "2f62eb5e7ebfe2917a84786ebccbd77c9afff9fb",
          "md5": "0c93af6fd85daf6f8720d1a2cea27edd"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "identity-iosarm64-0.5.1-sources.jar",
          "url": "identity-iosarm64-0.5.1-sources.jar",
          "size": 206603,
          "sha512": "57fe097dc70840e1cec523ea8b22d61c7b1df64c8013f398071c8a406e246cf8c5fce61bdfc020ee034739ea107f21f6fd608135292278e4f69ed24a405ff33c",
          "sha256": "aeb96ccf1d08e7c41c22a52f4078179e62e6237054f461acba953f8448da15b4",
          "sha1": "ff1c6ea74e32436f9114974735076b9e426a421d",
          "md5": "87288dc54e858912e4a73e4fa7e1828b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.iproov.kmp",
          "module": "sdk",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "identity-iosarm64-0.5.1-metadata.jar",
          "url": "identity-iosarm64-0.5.1-metadata.jar",
          "size": 72449,
          "sha512": "7adbb47ed2a11581b479edfc71f92976232a9c3e591baad8f90f10db7b5233897e7958d99de37bde557bda6226f93173f221586be15c33157ee707b3c2ac1c25",
          "sha256": "c9b3848199246201f8652970cd928fdb8fe2377b132362f5a7e185f612d8046c",
          "sha1": "291afbde534a286aecc75bc0e41e0c19762a01bb",
          "md5": "a2d22482c86f3e8ad63f172fc5b37b6e"
        }
      ]
    }
  ]
}
